import type { PublicBranding, PublicFeedbackContext, PublicQuestion } from "../../types/publicFeedback";

/** One fixture per QuestionType so the Templates page shows every control variant. */
export const TEMPLATE_GALLERY_FIXTURE_QUESTIONS: PublicQuestion[] = [
  {
    id: "__fixture_nps",
    question_key: "__fixture_nps",
    question_type: "nps",
    prompt: "NPS · How likely are you to recommend us to a friend?",
    help_text: "0 = not at all, 10 = extremely likely",
    is_required: false,
    is_pii: false,
    sort_order: 0,
    options: [],
  },
  {
    id: "__fixture_csat_5",
    question_key: "__fixture_csat_5",
    question_type: "csat_5",
    prompt: "CSAT (5) · Overall satisfaction",
    help_text: "Very Poor · Poor · Fair · Good · Excellent",
    is_required: false,
    is_pii: false,
    sort_order: 1,
    options: [],
  },
  {
    id: "__fixture_csat_4",
    question_key: "__fixture_csat_4",
    question_type: "csat_4",
    prompt: "CSAT (4) · Overall satisfaction",
    help_text: "Poor · Fair · Good · Excellent",
    is_required: false,
    is_pii: false,
    sort_order: 2,
    options: [],
  },
  {
    id: "__fixture_csat_2",
    question_key: "__fixture_csat_2",
    question_type: "csat_2",
    prompt: "CSAT (binary) · Would you visit again?",
    help_text: "Yes 👍🏾 · No 👎🏾",
    is_required: false,
    is_pii: false,
    sort_order: 3,
    options: [],
  },
  {
    id: "__fixture_single",
    question_key: "__fixture_single",
    question_type: "single_selection",
    prompt: "Single selection · What mattered most?",
    help_text: null,
    is_required: false,
    is_pii: false,
    sort_order: 4,
    options: [
      { id: "__fixture_single_a", value: "food", label: "Food quality", sort_order: 0 },
      { id: "__fixture_single_b", value: "service", label: "Service", sort_order: 1 },
      { id: "__fixture_single_c", value: "ambience", label: "Ambience", sort_order: 2 },
    ],
  },
  {
    id: "__fixture_multi",
    question_key: "__fixture_multi",
    question_type: "multi_selection",
    prompt: "Multi selection · What should we improve? (choose any)",
    help_text: null,
    is_required: false,
    is_pii: false,
    sort_order: 5,
    options: [
      { id: "__fixture_multi_a", value: "speed", label: "Speed", sort_order: 0 },
      { id: "__fixture_multi_b", value: "cleanliness", label: "Cleanliness", sort_order: 1 },
      { id: "__fixture_multi_c", value: "menu", label: "Menu variety", sort_order: 2 },
    ],
  },
  {
    id: "__fixture_plain",
    question_key: "__fixture_plain",
    question_type: "plain_text",
    prompt: "Plain text · Anything else we should know?",
    help_text: null,
    is_required: false,
    is_pii: false,
    sort_order: 6,
    options: [],
  },
  {
    id: "__fixture_short_text",
    question_key: "__fixture_short_text",
    question_type: "short_text",
    prompt: "Short text · What should we call you?",
    help_text: null,
    is_required: false,
    is_pii: false,
    sort_order: 7,
    options: [],
  },
  {
    id: "__fixture_phone",
    question_key: "__fixture_phone",
    question_type: "phone",
    prompt: "Phone · Best number to reach you",
    help_text: null,
    is_required: false,
    is_pii: false,
    sort_order: 8,
    options: [],
  },
  {
    id: "__fixture_email",
    question_key: "__fixture_email",
    question_type: "email",
    prompt: "Email · Where can we reply?",
    help_text: null,
    is_required: false,
    is_pii: false,
    sort_order: 9,
    options: [],
  },
  {
    id: "__fixture_dropdown",
    question_key: "__fixture_dropdown",
    question_type: "dropdown",
    prompt: "Dropdown · How did you hear about us?",
    help_text: null,
    is_required: false,
    is_pii: false,
    sort_order: 10,
    options: [
      { id: "__fixture_dd_a", value: "walk_in", label: "Walk-in", sort_order: 0 },
      { id: "__fixture_dd_b", value: "social", label: "Social media", sort_order: 1 },
      { id: "__fixture_dd_c", value: "friend", label: "Friend / referral", sort_order: 2 },
      { id: "__fixture_dd_d", value: "search", label: "Search / maps", sort_order: 3 },
    ],
  },
];

export function buildPreviewContextStub(
  branding: PublicBranding,
  overrides: Partial<Pick<PublicFeedbackContext, "survey" | "location" | "organization">> = {},
): Pick<PublicFeedbackContext, "branding" | "survey" | "location" | "organization"> {
  return {
    branding,
    survey: overrides.survey ?? {
      id: "preview",
      title: "All question types",
      slug: "preview",
      description: null,
      default_locale: "en",
    },
    location: overrides.location ?? {
      id: "preview-loc",
      name: "Downtown café",
      city: null,
      region: null,
    },
    organization: overrides.organization ?? {
      name: "Heritage Luxe Jewellers",
      address_line1: "12 Connaught Place",
      address_line2: "First Floor, Block A",
      city: "New Delhi",
      region: "Delhi",
      postal_code: "110001",
    },
  };
}
